/*
    display_ui.h

-----------------------------------------------------------------------------
  
  Copyright (c) 2017, MikroElektonika - http://www.mikroe.com

  All rights reserved.

----------------------------------------------------------------------------- */
/**
    \file     display_ui.h
    \brief    DISPLAY UI
    \defgroup DISPLAY_UI
    \brief    DISPLAY UI
    \{

| Global Library Prefix | **UI**                |
|:---------------------:|:---------------------:|
| Version               | **1.0.0**             |
| Date                  | **Feb 2019.**         |
| Developer             | **Milos Vidojevic**   |

---

**Version Info :**
- **1.0.0** Module Created [Milos Vidojevic]

*/
/* -------------------------------------------------------------------------- */

#ifndef _DISPLAY_UI_
#define _DISPLAY_UI_

/* -------------------------------------------------------- DISPLAY UI COLORS */

#define UI_BACKGROUND_COLOR             0x0000
#define UI_FONT_COLOR                   0xFFFF

#define UI_ACTIVE_COLOR                 0xDF25
#define UI_INACTIVE_COLOR               0x52AA
#define UI_COOLING_COLOR                0x001F
#define UI_HEATING_COLOR                0xF800

/* ------------------------------------------------------- DISPLAY UI CONTENT */

/*  
    Images / Logos
*/
extern const uint8_t                    AWS_LOGO_BMP[ 18438 ];
extern const uint8_t                    MIKROE_LOGO_BMP[ 18438 ];

/*  
    Fonts and text fields

Generated by MikroElektronika GLCD Font Creator 1.2.0.0
        
Small Font :
    - GLCD FontName : Courier_New7x11
    - GLCD FontSize : 7 x 11

Big Font :
    - GLCD FontName : Courier_New18x22
    - GLCD FontSize : 18 x 22

*/

extern const uint8_t                    UI_BIG_FONT[ ];
extern const uint8_t                    UI_SMALL_FONT[ ];

//  Current Temperature

#define UI_TEM_CUR_VAL_XOFF             26
#define UI_TEM_CUR_VAL_YOFF             41
#define UI_TEM_CUR_VAL_W                45
#define UI_TEM_CUR_VAL_H                21           

//  Current Humidity

#define UI_HUM_CUR_VAL_XOFF             26
#define UI_HUM_CUR_VAL_YOFF             73
#define UI_HUM_CUR_VAL_W                45
#define UI_HUM_CUR_VAL_H                21

//  Target Temperature

#define UI_TEM_TAR_VAL_XOFF             72
#define UI_TEM_TAR_VAL_YOFF             47
#define UI_TEM_TAR_VAL_W                23
#define UI_TEM_TAR_VAL_H                15

//  Target Humidity

#define UI_HUM_TAR_VAL_XOFF             72
#define UI_HUM_TAR_VAL_YOFF             79
#define UI_HUM_TAR_VAL_W                23
#define UI_HUM_TAR_VAL_H                15

/* 
    Images and illustrations

    Including monohromatic bitmap images, color bitmap images. Gener
*/

//  FAN Icon Setup - Illustration composed of 4 frames

#define UI_FAN_ICON_XOFF                1
#define UI_FAN_ICON_YOFF                4
#define UI_FAN_ICON_W                   22
#define UI_FAN_ICON_H                   24
#define UI_FAN_ICON_FRAMES              4

extern const uint8_t                    UI_FAN_ICON[ 4 ][ 72 ];

// Temperature Icon Setup

#define UI_TEM_ICON_XOFF                3
#define UI_TEM_ICON_YOFF                37
#define UI_TEM_ICON_W                   15
#define UI_TEM_ICON_H                   24

extern const uint8_t                    UI_TEM_ICON[ 48 ];

// Humidity Icon Setup

#define UI_HUM_ICON_XOFF                0
#define UI_HUM_ICON_YOFF                69
#define UI_HUM_ICON_W                   17
#define UI_HUM_ICON_H                   24

extern const uint8_t                    UI_HUM_ICON[ 72 ];

// FAN Intensity Icon - Ilustration composed of two icons

#define UI_WAV_ICON_XOFF                35
#define UI_WAV_ICON_YOFF                5
#define UI_WAV_ICON_W                   23
#define UI_WAV_ICON_H                   24

extern const uint8_t                    UI_WAV_ICON_LO[ 72 ];
extern const uint8_t                    UI_WAV_ICON_HI[ 72 ];

// Connection Icon

#define UI_CON_ICON_XOFF                70
#define UI_CON_ICON_YOFF                4
#define UI_CON_ICON_W                   22
#define UI_CON_ICON_H                   24
#define UI_CON_ICON_BMP_W               24
#define UI_CON_ICON_BMP_H               24

extern const uint8_t                    UI_CON_ICON[ 72 ];
extern const uint8_t                    UI_CON_ICON_BMP[ 1158 ];

/*
        UI_FAN_ICON_XOFF
        UI_TEM_ICON_XOFF
        UI_HUM_ICON_XOFF
        .
        .           UI_WAV_ICON_XOFF
        .           UI_TEM_CUR_VAL_XOFF
        .           UI_HUM_CUR_VAL_XOFF
        .           .
        .           .           UI_CON_ICON_XOFF
        .           .           UI_TEM_TAR_VAL_XOFF
        .           .           UI_HUM_TAR_VAL_XOFF
        .           .           .
    +---.-----------.-----------.-----------+
    |   .           .           .           |
    |   +-------+ . +-------+ . +-------+ . ------- DISPLAY_YOFF_FAN_ICON
    |   |       |   |       |   |       |   |       DISPLAY_YOFF_WAV_ICON
    |   |  FAN  |   |  WAV  |   |  CON  |   |       DISPLAY_YOFF_CON_ICON
    |   |       |   |       |   |       |   |
    |   +-------+   +-------+   +-------+   |
    |   .           .           .           |
    |   +-------+ . +-------+ . +-------+ . ------- DISPLAY_YOFF_TEM_ICON
    |   |       |   |       |   |       |   |       DISPLAY_YOFF_TEM_CUR_VAL
    |   |  TEM  |   |"T CUR"|   |"T TAR"|   |       DISPLAY_YOFF_TEM_TAR_VAL
    |   |       |   |       |   |       |   |
    |   +-------+   +-------+   +-------+   |
    |   .           .           .           |
    |   +-------+ . +-------+ . +-------+ . ------- DISPLAY_YOFF_HUM_ICON
    |   |       |   |       |   |       |   |       DISPLAY_YOFF_HUM_CUR_VAL
    |   |  HUM  |   |"H CUR"|   |"H TAR"|   |       DISPLAY_YOFF_HUM_TAR_VAL
    |   |       |   |       |   |       |   |
    |   +-------+   +-------+   +-------+   |
    |                                       |
    +---------------------------------------+


 ---------------------------------------------------------------------------- */

#endif

